Fix nsupdate 'server' param, always pass IP
This change, if applied, fixes all 'nsupdate' invocations and makes sure the IP
address is used, not the DNS name.

This change fixes the following error that happens in some recent versions of ansible:

> dns.exception.SyntaxError: Text input is malformed.

Co-authored-by: Eric L <ericzolf@users.noreply.github.com>
Co-authored-by: Evgeni Golov <evgeni@golov.de>